#!/usr/bin/env bash
# utils/init.sh — lean RUNTIME init for the binary-classifier pipeline on UCloud.
#
# Works as the Initialization Bash script for a Terminal / PyTorch / JupyterLab
# job, and as a manual `bash utils/init.sh`. It waits for /work mount, finds and
# sources .env on the project drive, exports runtime env (HF_HOME, UV_*),
# installs uv, writes env.sh, configures git, pulls the latest code, creates
# data symlinks, and syncs the Python env. Assumes the repo is already cloned
# on the project drive and .env exists at its root.
#
# It does NOT install editors or agent harnesses — that is the optional
# `utils/devenv.sh` overlay (interactive SSH only), kept decoupled so GPU/batch
# jobs stay lean.
set -euo pipefail

# Pre-pull the open-weight annotator weights into the shared HF cache. Leave 0
# on every job EXCEPT the vLLM annotation job (stage 03 open-weight arm); the
# model id is read from config/religious_missions.yaml, never hardcoded here.
PREPULL_MODEL=0

# ─── Wait for the /work mount ─────────────────────────────────────────────────

echo "--- Waiting for /work mount ---"
TIMEOUT=60
ELAPSED=0
until [ -d "/work" ] && [ -n "$(ls -A /work 2>/dev/null)" ]; do
  sleep 2
  ELAPSED=$((ELAPSED + 2))
  if [ "${ELAPSED}" -ge "${TIMEOUT}" ]; then
    echo "ERROR: /work not mounted after ${TIMEOUT}s." >&2
    exit 1
  fi
done
echo "--- /work ready after ${ELAPSED}s ---"

# ─── Find and source .env on the project drive ────────────────────────────────
# After the mount is up, scan /work for a subdirectory containing .env. This is
# the single source of truth for all config: drive names, git identity, LLM
# serving, and secrets. Only one drive should have .env — fail loud if missing.
ENV_FILE=""
for d in /work/*/; do
  if [ -f "${d}.env" ]; then
    ENV_FILE="${d}.env"
    PROJECT_DRIVE="$(basename "${d}")"
    echo "--- Found .env on /work/${PROJECT_DRIVE} ---"
    break
  fi
done

if [ -z "${ENV_FILE}" ]; then
  echo "ERROR: .env not found under /work/." >&2
  echo "       Create it on the project drive before starting the job." >&2
  echo "       See docs/RUNNING_ON_UCLOUD.md §2 step 7." >&2
  exit 1
fi

echo "--- Sourcing ${ENV_FILE} ---"
set -a && . "${ENV_FILE}" && set +a

# Derive all paths from (now populated) config values.
DATA="/work/${DATA_DRIVE}"
PROJECT="/work/${PROJECT_DRIVE}"
REPO_DIR="${PROJECT}"
ENV_FILE="${PROJECT}/.env"
ENV_SH="${PROJECT}/env.sh"

# ─── Assert both Drives are mounted (fatal if absent) ─────────────────────────

for drive in "${DATA}" "${PROJECT}"; do
  if [ ! -d "${drive}" ]; then
    echo "ERROR: expected Drive not found at ${drive}" >&2
    echo "       Attach it to the job and set DATA_DRIVE / PROJECT_DRIVE in" >&2
    echo "       .env on the project drive — observe the actual names under /work:" >&2
    ls -la /work/ >&2 || true
    exit 1
  fi
done
echo "--- Drives OK: ${DATA} , ${PROJECT} ---"

# ─── Install uv if missing (UCloud usually ships it pre-installed) ────────────

if ! command -v uv >/dev/null 2>&1; then
  echo "--- Installing uv ---"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="${HOME}/.local/bin:${PATH}"

# ─── Export runtime env for THIS shell ────────────────────────────────────────
# HF_HOME covers both the transformer encoders and the vLLM open-weight download
# so encoders and the Gemma annotator share one reusable cache across projects.
# The uv cache lives on the data drive but .venv lives on the project drive
# (separate mounts), so hardlinks fail — UV_LINK_MODE=copy makes the fallback
# explicit and quiet (the cache still avoids re-downloads).
export HF_HOME="${DATA}/hf-cache"
export UV_CACHE_DIR="${DATA}/uv-cache"
export UV_PYTHON_INSTALL_DIR="${DATA}/uv-python"
export UV_LINK_MODE=copy

# ─── Write the lean runtime env.sh and auto-source it on every login ──────────
# Generated with the resolved absolute /work paths baked in; $HOME/$PATH stay
# literal so they evaluate at login time. Kept lean — the dev/agent overlay
# writes its OWN sourced file so batch jobs never pick up the harness env.
echo "--- Writing ${ENV_SH} ---"
cat >"${ENV_SH}" <<EOF
# env.sh — runtime environment for the binary-classifier pipeline on UCloud.
# Auto-generated by utils/init.sh. Sourced by ~/.bashrc, ~/.profile, utils/run.sh.
export HF_HOME="${DATA}/hf-cache"
export UV_CACHE_DIR="${DATA}/uv-cache"
export UV_PYTHON_INSTALL_DIR="${DATA}/uv-python"
export UV_LINK_MODE=copy
export PATH="\$HOME/.local/bin:\$PATH"
[ -f "${ENV_FILE}" ] && set -a && . "${ENV_FILE}" && set +a
EOF

SOURCE_LINE="[ -f '${ENV_SH}' ] && source '${ENV_SH}'"
for rc in "${HOME}/.bashrc" "${HOME}/.profile" "${HOME}/.bash_profile"; do
  grep -qF "${ENV_SH}" "${rc}" 2>/dev/null || echo "${SOURCE_LINE}" >>"${rc}"
done

# ─── Git identity + HTTPS credential helper (no token in URLs or history) ─────

git config --global user.name "${GIT_NAME}"
git config --global user.email "${GIT_EMAIL}"
git config --global credential.helper store
if [ -n "${GITHUB_TOKEN:-}" ]; then
  printf 'https://%s:x-oauth-basic@github.com\n' "${GITHUB_TOKEN}" >"${HOME}/.git-credentials"
  chmod 600 "${HOME}/.git-credentials"
fi

# ─── cwd is load-bearing: PathRegistry anchors at the current directory ───────

cd "${REPO_DIR}"
git pull --ff-only || echo "WARNING: 'git pull --ff-only' failed (network, auth, or local changes). Check stderr above." >&2

# ─── Pre-create directories on the DATA_DRIVE ─────────────────────────────────
# data/raw is the only symlink — it points to the shared cross-project data drive.
# Everything else (data/interim, data/models, data/processed/*) lives as real
# directories inside the repo on the project drive, which persists across jobs.
# PathRegistry.ensure_dirs() creates the nested dirs on first use.
mkdir -p "${DATA}/raw" "${DATA}/hf-cache" "${DATA}/uv-cache" "${DATA}/uv-python"

# ─── Create the data/raw symlink (idempotent) ─────────────────────────────────
# Clear any wrong-type path first, then symlink.
if [ -e "data/raw" ] && [ ! -L "data/raw" ]; then
  rm -rf data/raw
fi
mkdir -p data
ln -sfn "${DATA}/raw" data/raw

echo "--- Symlink ---"
ls -l data/raw

# ─── Python environment ───────────────────────────────────────────────────────
# System Python is 3.12; the project requires 3.13. `uv sync` includes the `dev`
# group by default (ruff + ty), so verification step 4 works out of the box.
# Add `--extra serve` ONLY on the vLLM annotation job.
if ! uv python install 3.13; then
  echo "WARNING: 'uv python install 3.13' failed. 'uv sync' may fail if 3.13 is unavailable." >&2
fi
uv sync

# ─── Optional: pre-pull the open-weight annotator into the shared HF cache ────
# Single switch point: the model id is derived from the YAML's vLLM candidate,
# never hardcoded. Skips cleanly if the vLLM arm is commented out.
if [ "${PREPULL_MODEL}" -eq 1 ]; then
  MODEL_ID="$(uv run python -c "from binary_classifier.config import load_config; print(next((c.id for c in load_config('config/religious_missions.yaml').model_slate.bakeoff_candidates if c.provider=='vllm'), ''))")"
  if [ -n "${MODEL_ID}" ]; then
    echo "--- Pre-pulling ${MODEL_ID} into ${HF_HOME} ---"
    uv run hf download "${MODEL_ID}"
  else
    echo "--- No vLLM candidate in config; skipping model pre-pull. ---"
  fi
fi

echo "=== init.sh complete $(date) ==="
echo "Open a new shell (or 'source ${ENV_SH}') and the runtime env is loaded."
